version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api-express
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:1@postgres:5432/postgres?schema=public

volumes:
  pgdata:
